# Import the admin module from django.contrib to enable the admin interface
from django.contrib import admin

# Import path and include functions from django.urls to define URL patterns
from django.urls import path, include

# Import DefaultRouter from rest_framework.routers to automatically generate URL patterns for viewsets
from rest_framework.routers import DefaultRouter

# Import UserViewSet from users.views to handle CRUD operations for User model
from users.views import UserViewSet

# Import TaskViewSet from tasks.views to handle CRUD operations for Task model
from tasks.views import TaskViewSet

# Create an instance of DefaultRouter
router = DefaultRouter()

# Register the UserViewSet with the router under the 'users' URL prefix
router.register(r'users', UserViewSet)

# Register the TaskViewSet with the router under the 'tasks' URL prefix
router.register(r'tasks', TaskViewSet)

# Define the URL patterns for the project
urlpatterns = [
    # Route for the admin interface
    path('admin/', admin.site.urls),
    
    # Route for the API endpoints, including all URLs generated by the router
    path('api/', include(router.urls)),
    path('api/', include('users.urls')),  # Include users URLs
]